#!/bin/bash

# b2 access credentials.
/usr/bin/defaults write /Library/Preferences/ManagedInstalls B2AccountID -string "ACCOUNT_ID"
/usr/bin/defaults write /Library/Preferences/ManagedInstalls B2ApplicationKey -string "APPLICATION_KEY"

# Seconds a b2 request is valid for - default is 1800 (30 min)
#/usr/bin/defaults write /Library/Preferences/ManagedInstalls B2ValidDuration -int 3600
